import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        I'm a third-year student at the University of Toronto where
        I am pursuing a bachelor's degree in Mathematics with minors
        in Computer Science and Philosophy with a heavy focus on logic.
      </main>
    </div>
  )
}
